spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/movieflow
    # 192.168.0.144:3306 빌드 시 꼭 수정
    username: root
    password: green502

mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  swagger-ui:
    path: /swagger.html

server:
  port: 8082
